# Generated by Django 5.0.6 on 2024-05-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('positive', models.DecimalField(decimal_places=3, max_digits=4)),
                ('negative', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
