# Generated by Django 5.0.6 on 2024-05-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_remove_sentimentanalysis_negative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='sentiment',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
