# Generated by Django 5.0.6 on 2024-05-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_sentimentanalysis_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='sentiment',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
    ]
